services:
  app:
    build: .
    container_name: parking-app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
   
    read_only: true
    tmpfs:
      - /tmp
      - /var/lock/apache2
      - /var/run/apache2
      - /var/log/apache2
    restart: unless-stopped
